---
  dataset: ???
  model: ???
  training:
    num_iters: 200
    N: 2
    M: 2
    Ks: [3,10,30,100,300,1000,3000,10000]
    num_runs: 5
    pred_ll:
      do_pred_ll: False
      num_pred_ll_samples: 1000
    lr: 1e-3
    ML: 1
