---
  dataset: ???
  model: ???
  training:
    num_iters: 3000
    N: 2
    M: 2
    Ks: [1,3,10,30,100]
    num_runs: 10
    pred_ll:
      do_pred_ll: True
      num_pred_ll_samples: 1000
    lr: 1e-3
    ML: 1
  use_data: True
